routes/web.php
Route::get('/cart-checkout','FrontendController@cartCheckout')->name('cart.checkout');
Route::get('/cart-to-pay','FrontendController@cartToPay')->name('cart.to_pay');
Route::get('/cart-clear','FrontendController@cartClear')->name('cart.clear');

Route::get('stripe', 'StripePaymentController@stripe')->name('stripe');
Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');

Route::get('/home', 'FrontendController@index');
Route::get('/about-us','FrontendController@aboutUs')->name('about.us');
Route::get('/emi-calculator','FrontendController@emiCalculator')->name('emi.calculator');
Route::get('/wood-creation','FrontendController@woodCreation')->name('wood.creation');
// Route::get('/blog','FrontendController@ourBlog')->name('our.blog');
Route::get('/contact','FrontendController@contact')->name('contact');
Route::post('/contact/message','MessageController@store')->name('contact.store');
Route::get('product-detail/{slug}','FrontendController@productDetail')->name('product-detail');
Route::post('/product/search','FrontendController@productSearch')->name('product.search');
Route::get('/product-cat/{slug}','FrontendController@productCat')->name('product-cat');
Route::get('/product-sub-cat/{slug}/{sub_slug}','FrontendController@productSubCat')->name('product-sub-cat');
Route::get('/product-brand/{slug}','FrontendController@productBrand')->name('product-brand');
// Cart section
Route::get('/add-to-cart/{slug}','CartController@addToCart')->name('add-to-cart')->middleware('user');
Route::post('/add-to-cart','CartController@singleAddToCart')->name('single-add-to-cart')->middleware('user');
Route::get('cart-delete/{id}','CartController@cartDelete')->name('cart-delete');
Route::post('cart-update','CartController@cartUpdate')->name('cart.update');

Route::get('/cart',function(){
    return view('frontend.pages.cart');
})->name('cart');
Route::get('/checkout','CartController@checkout')->name('checkout')->middleware('user');
// Wishlist
Route::get('/wishlist',function(){
    return view('frontend.pages.wishlist');
})->name('wishlist');
Route::get('/wishlist/{slug}','WishlistController@wishlist')->name('add-to-wishlist')->middleware('user');
Route::get('wishlist-delete/{id}','WishlistController@wishlistDelete')->name('wishlist-delete');
Route::post('cart/order','OrderController@store')->name('cart.order');
Route::get('order/pdf/{id}','OrderController@pdf')->name('order.pdf');
Route::get('/income','OrderController@incomeChart')->name('product.order.income');
// Route::get('/user/chart','AdminController@userPieChart')->name('user.piechart');
Route::get('/product-grids','FrontendController@productGrids')->name('product-grids');
Route::get('/product-lists','FrontendController@productLists')->name('product-lists');
// Route::match(['get','post'],'/filter','FrontendController@productFilter')->name('shop.filter');
// Order Track
Route::get('/product/track','OrderController@orderTrack')->name('order.track');
Route::post('product/track/order','OrderController@productTrackOrder')->name('product.track.order');
// Blog
Route::get('/blog','FrontendController@blog')->name('blog');
Route::get('/blog-detail/{slug}','FrontendController@blogDetail')->name('blog.detail');
Route::get('/blog/search','FrontendController@blogSearch')->name('blog.search');
Route::post('/blog/filter','FrontendController@blogFilter')->name('blog.filter');
Route::get('blog-cat/{slug}','FrontendController@blogByCategory')->name('blog.category');
Route::get('blog-tag/{slug}','FrontendController@blogByTag')->name('blog.tag');

// NewsLetter
Route::post('/subscribe','FrontendController@subscribe')->name('subscribe');

// Product Review
Route::resource('/review','ProductReviewController');
Route::post('product/{slug}/review','ProductReviewController@store')->name('review.store');

// Post Comment
Route::post('post/{slug}/comment','PostCommentController@store')->name('post-comment.store');
Route::resource('/comment','PostCommentController');
// Coupon
Route::post('/coupon-store','CouponController@couponStore')->name('coupon-store');
// Payment
Route::get('payment', 'PayPalController@payment')->name('payment');
Route::get('cancel', 'PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'PayPalController@success')->name('payment.success');



// Backend section start

Route::group(['prefix'=>'/admin','middleware'=>['auth','admin']],function(){
    Route::get('/','AdminController@index')->name('admin');
    Route::get('/file-manager',function(){
        return view('backend.layouts.file-manager');
    })->name('file-manager');
    // user route
    Route::resource('users','UsersController');
    // Banner
    Route::resource('banner','BannerController');
    // Brand
    Route::resource('/brand','BrandController');
    // Profile
    // Product Instalment
    Route::resource('/product-instalment','InstalmentController');
    Route::get('/profile','AdminController@profile')->name('admin-profile');
    Route::post('/profile/{id}','AdminController@profileUpdate')->name('profile-update');
    // Category
    Route::resource('/category','CategoryController');
    // Product
    Route::resource('/product','ProductController');
    // Product Instalment
    Route::resource('/product-instalment','InstalmentController');
    // Ajax for sub category
    Route::post('/category/{id}/child','CategoryController@getChildByParent');
    // POST category
    Route::resource('/post-category','PostCategoryController');
    // Post tag
    Route::resource('/post-tag','PostTagController');
    // Post
    Route::resource('/post','PostController');
    // Message
    Route::resource('/message','MessageController');
    Route::get('/message/five','MessageController@messageFive')->name('messages.five');

    // Order
    Route::resource('/order','OrderController');
    // Shipping
    Route::resource('/shipping','ShippingController');
    // Coupon
    Route::resource('/coupon','CouponController');
    // Settings
    Route::get('settings','AdminController@settings')->name('settings');
    Route::post('setting/update','AdminController@settingsUpdate')->name('settings.update');

    // Notification
    Route::get('/notification/{id}','NotificationController@show')->name('admin.notification');
    Route::get('/notifications','NotificationController@index')->name('all.notification');
    Route::delete('/notification/{id}','NotificationController@delete')->name('notification.delete');
    // Password Change
    Route::get('change-password', 'AdminController@changePassword')->name('change.password.form');
    Route::post('change-password', 'AdminController@changPasswordStore')->name('change.password');

// vendor
Route::get('vendors_page','VendorController@index')->name('vendor_page');
Route::get('vendor_create','VendorController@create')->name('vendor_create');
Route::post('vendor_save','VendorController@store')->name('vendor_store');
Route::get('vendor_edit/{id}','VendorController@edit')->name('vendor_edit');
Route::post('vendor_update/{id}','VendorController@update')->name('vendor_update');
Route::delete('vendor_delete/{id}','VendorController@destroy')->name('vendor_destroy');

// vendor Category

Route::get('/vendors_catg_page','VendorCategoryController@index')->name('vendor_catg_page');
Route::get('/vendor_catg_create','VendorCategoryController@create')->name('vendor_catg_create');
Route::post('/vendor_catg_save','VendorCategoryController@store')->name('vendor_catg_store');
Route::get('/vendor_catg_edit/{id}','VendorCategoryController@edit')->name('vendor_catg_edit');
Route::post('/vendor_catg_update/{id}','VendorCategoryController@update')->name('vendor_catg_update');
Route::delete('vendor_catg_delete/{id}','VendorCategoryController@destroy')->name('vendor_catg_destroy');



    // Api Part
    Route::get('/warehouse', 'HomeController@warehouse')->name('warehouse');

    // Route::get('/productEdit/{id}', 'ProductController@editProduct')->name('edit.product');
    Route::post('/productUpdate', 'ProductController@updateProductImages')->name('update.product');

});

// User section start
Route::group(['prefix'=>'/user','middleware'=>['user']],function(){
    Route::get('/','HomeController@index')->name('user');
     // Profile
     Route::get('/profile','HomeController@profile')->name('user-profile');
     Route::post('/profile/{id}','HomeController@profileUpdate')->name('user-profile-update');
    //  Order
    Route::get('/order',"HomeController@orderIndex")->name('user.order.index');
    Route::get('/order/show/{id}',"HomeController@orderShow")->name('user.order.show');
    Route::delete('/order/delete/{id}','HomeController@userOrderDelete')->name('user.order.delete');
    // Product Review
    Route::get('/user-review','HomeController@productReviewIndex')->name('user.productreview.index');
    Route::delete('/user-review/delete/{id}','HomeController@productReviewDelete')->name('user.productreview.delete');
    Route::get('/user-review/edit/{id}','HomeController@productReviewEdit')->name('user.productreview.edit');
    Route::patch('/user-review/update/{id}','HomeController@productReviewUpdate')->name('user.productreview.update');

    // Post comment
    Route::get('user-post/comment','HomeController@userComment')->name('user.post-comment.index');
    Route::delete('user-post/comment/delete/{id}','HomeController@userCommentDelete')->name('user.post-comment.delete');
    Route::get('user-post/comment/edit/{id}','HomeController@userCommentEdit')->name('user.post-comment.edit');
    Route::patch('user-post/comment/udpate/{id}','HomeController@userCommentUpdate')->name('user.post-comment.update');

    // Password Change
    Route::get('change-password', 'HomeController@changePassword')->name('user.change.password.form');
    Route::post('change-password', 'HomeController@changPasswordStore')->name('change.password');

});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {

app/Models/Instalment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Instalment extends Model
{
    public $fillable = ['product_id', 'instalment_duration', 'advanced_payment', 'instalment_price'];

    public function products(){
        return $this->belongsToMany(Product::class,'product_id');
    }

}

app/Http/Controllers/InstalmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Brand;
use App\Models\Instalment;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;

class InstalmentController extends Controller
{

    public function index()
    {
        $instalments = Instalment::all();
        return view('backend.instalment.index',compact('instalments'));
    }

    public function create()
    {
        $products = Product::all();
        return view('backend.instalment.create', compact('products'));
    }

    public function store(Request $request)
    {
        for($i =0; $i<count($request->data['instalment_duration']); $i++){
            $instalment = Instalment::create([
                'product_id' => $request->product_id,
                'instalment_duration' => $request->data['instalment_duration'][$i],
                'advanced_payment' => $request->data['advanced_payment'][$i],
                'instalment_price' => $request->data['instalment_price'][$i],
            ]);
        }
        request()->session()->flash('success','Instalment data successfully added');
        return redirect()->route('product-instalment.index');
    }

    public function show(Instalment $instalment)
    {

    }

    public function edit($id)
    {
        $product = Product::all();
        $instalment = Instalment::find($id);
        return view('backend.instalment.edit')->with('instalment',$instalment)
                                              ->with('instalments',$product);
    }

    public function update(Request $request,  $id)
    {
        $instalment = Instalment::find($id);
        $status = Instalment::where('id', $id)
        ->update(
            [
                'product_id' => $request->product_id,
                'instalment_duration' => $request->instalment_duration,
                'advanced_payment' => $request->advanced_payment,
                'instalment_price' => $request->instalment_price
            ]);


        if($status){
            request()->session()->flash('success','data  successfully updated');
        }
        else{
            request()->session()->flash('error','Error occurred, Please try again!');
        }
        return redirect()->route('product-instalment.index');
    }

    public function destroy(Instalment $instalment)
    {
    }
}

resources/views/backend/instalment/create.blade.php
@extends('backend.layouts.master')
@push('style')
<style>
    .form-control{
        margin-right:10px;
    }
    .margin-row{
        margin-bottom: 10px;
    }
</style>
@endpush

@section('main-content')

<div class="card">
    <h5 class="card-header">Add Product Instalment</h5>
    <div class="card-body">
      <form method="post" action="{{route('product-instalment.store')}}"   enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="inputTitle" class="col-form-label">Select Product <span class="text-danger">*</span></label>
          <select name="product_id" class="form-control" >
              <option value="">--Select Condition--</option>
              @foreach ($products as $product)
                 <option value="{{$product->id}}">{{$product->title}}</option>
              @endforeach
          </select>
        </div>
        <div class="col-lg-12 p-0">
            <div id="inputFormRow" class="d-flex margin-row">
                <input type="text" name="data[instalment_duration][]" class="form-control m-input" placeholder="Instalment duration " autocomplete="off">
                <input type="text" name="data[instalment_price][]" class="form-control m-input" placeholder="Instalment Price" autocomplete="off">
                <input type="text" name="data[advanced_payment][]" class="form-control m-input" placeholder="Advance Payment" autocomplete="off">
                <button id="removeRow" type="button" class="btn btn-danger">Remove</button>
            </div>
            <div id="newRow"></div>
            <button id="addRow" type="button" class="btn btn-info">Add Row</button>
        </div>
        <div class="form-group mb-3 mt-2">
          <button type="reset" class="btn btn-warning">Reset</button>
           <button class="btn btn-success" type="submit">Submit</button>
        </div>
      </form>
    </div>
</div>

@endsection

@push('styles')
<link rel="stylesheet" href="{{asset('backend/summernote/summernote.min.css')}}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
@endpush
@push('scripts')
<script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
<script src="{{asset('backend/summernote/summernote.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<script>
    $('#lfm').filemanager('image');

    $(document).ready(function() {
      $('#summary').summernote({
        placeholder: "Write short description.....",
          tabsize: 2,
          height: 100
      });
    });

    $(document).ready(function() {
      $('#description').summernote({
        placeholder: "Write detail description.....",
          tabsize: 2,
          height: 150
      });
    });
    // $('select').selectpicker();

</script>

<script>
  $('#cat_id').change(function(){
    var cat_id=$(this).val();
    // alert(cat_id);
    if(cat_id !=null){
      // Ajax call
      $.ajax({
        url:"/admin/category/"+cat_id+"/child",
        data:{
          _token:"{{csrf_token()}}",
          id:cat_id
        },
        type:"POST",
        success:function(response){
          if(typeof(response) !='object'){
            response=$.parseJSON(response)
          }
          // console.log(response);
          var html_option="<option value=''>----Select sub category----</option>"
          if(response.status){
            var data=response.data;
            // alert(data);
            if(response.data){
              $('#child_cat_div').removeClass('d-none');
              $.each(data,function(id,title){
                html_option +="<option value='"+id+"'>"+title+"</option>"
              });
            }
            else{
            }
          }
          else{
            $('#child_cat_div').addClass('d-none');
          }
          $('#child_cat_id').html(html_option);
        }
      });
    }
    else{
    }
  })
</script>

<script type="text/javascript">
    // add row
    $("#addRow").click(function () {
        var html = '';
        html += '<div id="inputFormRow">';
        html += '<div class="input-group mb-3">';
        html += '<input type="text" name="data[instalment_duration][]" class="form-control m-input" placeholder="Enter title" autocomplete="off">';
        html += '<input type="text" name="data[instalment_price][]" class="form-control m-input" placeholder="Enter title" autocomplete="off">';
        html += '<input type="text" name="data[advanced_payment][]" class="form-control m-input" placeholder="Enter title" autocomplete="off">';
        html += '<div class="input-group-append">';
        html += '<button id="removeRow" type="button" class="btn btn-danger">Remove</button>';
        html += '</div>';
        html += '</div>';

        $('#newRow').append(html);
    });

    // remove row
    $(document).on('click', '#removeRow', function () {
        $(this).closest('#inputFormRow').remove();
    });
</script>
@endpush

resources/views/backend/instalment/edit.blade.php
@extends('backend.layouts.master')
@push('style')
<style>
    .form-control{
        margin-right:10px;
    }
    .margin-row{
        margin-bottom: 10px;
    }
</style>
@endpush

@section('main-content')

<div class="card">
    <h5 class="card-header">Add Product</h5>
    <div class="card-body">
      <form method="post" action="{{route('product-instalment.update',$instalment->id)}}"   enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
          <label for="inputTitle" class="col-form-label"> Product <span class="text-danger">*</span></label>
          <select name="product_id" class="form-control" >
              <option value="">--Select Condition--</option>

              @foreach($instalments as $product)
              <option {{ ($product->id) == $instalment->product_id ? 'selected' : '' }} value="{{$product->id}}">{{$product->title}}</option>
              @endforeach
          </select>
        </div>
        <div class="col-lg-12 p-0">
            <div id="inputFormRow" class="d-flex margin-row">
                <input type="text" name="instalment_duration[]" class="form-control m-input" placeholder="Instalment duration " value="{{$instalment->instalment_duration}}" autocomplete="off">
                <input type="text" name="instalment_price[]" class="form-control m-input" placeholder="Instalment Price" value="{{$instalment->instalment_price}}"  autocomplete="off">
                <input type="text" name="advanced_payment[]" class="form-control m-input" placeholder="Advance Payment" value="{{$instalment->advanced_payment}}"  autocomplete="off">

            </div>
        </div>
        <div class="form-group mb-3 mt-2">
           <button class="btn btn-success" type="submit">Submit</button>
        </div>
      </form>
    </div>
</div>

@endsection

@push('styles')
<link rel="stylesheet" href="{{asset('backend/summernote/summernote.min.css')}}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
@endpush
@push('scripts')
<script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
<script src="{{asset('backend/summernote/summernote.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<script>
    $('#lfm').filemanager('image');

    $(document).ready(function() {
      $('#summary').summernote({
        placeholder: "Write short description.....",
          tabsize: 2,
          height: 100
      });
    });

    $(document).ready(function() {
      $('#description').summernote({
        placeholder: "Write detail description.....",
          tabsize: 2,
          height: 150
      });
    });
    // $('select').selectpicker();

</script>

<script>
  $('#cat_id').change(function(){
    var cat_id=$(this).val();
    // alert(cat_id);
    if(cat_id !=null){
      // Ajax call
      $.ajax({
        url:"/admin/category/"+cat_id+"/child",
        data:{
          _token:"{{csrf_token()}}",
          id:cat_id
        },
        type:"POST",
        success:function(response){
          if(typeof(response) !='object'){
            response=$.parseJSON(response)
          }
          // console.log(response);
          var html_option="<option value=''>----Select sub category----</option>"
          if(response.status){
            var data=response.data;
            // alert(data);
            if(response.data){
              $('#child_cat_div').removeClass('d-none');
              $.each(data,function(id,title){
                html_option +="<option value='"+id+"'>"+title+"</option>"
              });
            }
            else{
            }
          }
          else{
            $('#child_cat_div').addClass('d-none');
          }
          $('#child_cat_id').html(html_option);
        }
      });
    }
    else{
    }
  })
</script>


@endpush

resources/views/backend/instalment/index.blade.php
@extends('backend.layouts.master')

@section('main-content')
 <!-- DataTales Example -->
 <div class="card shadow mb-4">
     <div class="row">
         <div class="col-md-12">
            @include('backend.layouts.notification')
         </div>
     </div>
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary float-left">Product Instalment</h6>
      <a href="{{route('product-instalment.create')}}" class="btn btn-primary btn-sm float-right" data-toggle="tooltip" data-placement="bottom" title="Add User"><i class="fas fa-plus"></i> Add Product Instalment</a>
    </div>
    <div class="card-body">
      <div class="table-responsive">

        <table class="table table-bordered" id="product-dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>S.N.</th>
              <th>Duration </th>
              <th>Price </th>
              <th>Advance Payment </th>
              <th>Action</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>S.N.</th>
              <th>Duration </th>
              <th>Price </th>
              <th>Advance Payment </th>
              <th>Action</th>
            </tr>
          </tfoot>
          <tbody>
            @foreach($instalments as $instalment)
                <tr>
                    <td>{{$instalment->id}}</td>
                    <td>{{$instalment->instalment_duration}}</td>
                    <td>{{$instalment->advanced_payment}}</td>
                    <td>{{$instalment->instalment_price}}</td>
                    <td>
                        <a href="{{route('product-instalment.edit',$instalment->id)}}" class="btn btn-primary btn-sm float-left mr-1" style="height:30px; width:30px;border-radius:50%" data-toggle="tooltip" title="edit" data-placement="bottom"><i class="fas fa-edit"></i></a>
                            <form method="POST" action="{{route('product-instalment.destroy',[$instalment->id])}}">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger btn-sm dltBtn" data-id={{$instalment->id}} style="height:30px; width:30px;border-radius:50%" data-toggle="tooltip" data-placement="bottom" title="Delete"><i class="fas fa-trash-alt"></i></button>
                            </form>
                    </td>
                </tr>
            @endforeach
          </tbody>
        </table>

      </div>
    </div>
</div>
@endsection

@push('styles')
  <link href="{{asset('backend/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
  <style>
      div.dataTables_wrapper div.dataTables_paginate{
          display: none;
      }
      .zoom {
        transition: transform .2s; /* Animation */
      }

      .zoom:hover {
        transform: scale(5);
      }
  </style>
@endpush

@push('scripts')

  <!-- Page level plugins -->
  <script src="{{asset('backend/vendor/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('backend/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="{{asset('backend/js/demo/datatables-demo.js')}}"></script>
  <script>

      $('#product-dataTable').DataTable( {
        "scrollX": false
            "columnDefs":[
                {
                    "orderable":false,
                    "targets":[10,11,12]
                }
            ]
        } );

        // Sweet alert

        function deleteData(id){

        }
  </script>
  <script>
      $(document).ready(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
          $('.dltBtn').click(function(e){
            var form=$(this).closest('form');
              var dataID=$(this).data('id');
              // alert(dataID);
              e.preventDefault();
              swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover this data!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                       form.submit();
                    } else {
                        swal("Your data is safe!");
                    }
                });
          })
      })
  </script>
@endpush